sonar.host.url=http://sonarqube.choicetechlab.com
# must be unique in a given SonarQube instance
sonar.projectKey=shivmitra-react-frontend
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=shivmitra-react-frontend
sonar.projectVersion=0.0.1
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.login=2c0c06be6454c33cea57779be8e46186ddbcf2ef
# Path to source directories
sonar.sources=src

# Path to test directories
sonar.tests=src

# File extensions to be included in the analysis
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx

# File extensions to be excluded from the analysis
sonar.exclusions=node_modules/**, build/**, public/**, **/*.spec.js, **/*.spec.jsx, **/*.spec.ts, **/*.spec.tsx

# Test file patterns
sonar.test.inclusions=**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx

# Source encoding
sonar.sourceEncoding=UTF-8

# Optional: Add additional properties as needed
sonar.typescript.tsconfigPath=tsconfig.json